### ISSUE TITLE
RG tags

### ISSUE THREAD

**Issue by calkan** [vpc-ccg/lordfast#13]
setting RG tags while mapping would be good to have.

**Comment by haghshenas** [comment]
Hi Can,

Is RG something that the mapper should detect automatically?
Or the user is expected to pass it as a command line argument?
I can see this option from BWA-MEM:
```
    -R STR        read group header line such as '@RG\tID:foo\tSM:bar' [null]
```
are you suggesting something similar?

**Comment by calkan** [comment]
You cannot detect it, it has to be user specified. I want it similar to BWA.

**Comment by haghshenas** [comment]
I see. Thanks for clarification.
I'll add this feature later today.

**Comment by haghshenas** [comment]
I added an option (-R/--readGroup) to pass the read group line.
Please let me know if it works as you expect.

**Comment by calkan** [comment]
almost. Unmapped reads dont have RG in this implementation. They should also include the RG info

**Comment by haghshenas** [comment]
You were right. I fixed it.
Thank you.
