### ISSUE TITLE
fasta query not supported, or gzip not supported, or reads all input to mem, and crashes

### ISSUE THREAD

**Issue by calkan** [vpc-ccg/lordfast#7]
one of these cause a crash. Probably the .gz one, or fasta, or both:

cmdline (reads10.fasta is just 10 reads)

lordfast --search hg19/hg19.fasta --seq /mnt/storage1/projects/giab/pacbio/NA12878_PacBio_MtSinai/reads10.fasta -t 32

......
| *Reading Input* |            0.00 | XXXXXXXXXXXXXXX |         1466.70 | XXXXXXXXXXXXXXX               9 |
Floating point exception (core dumped)

**Comment by haghshenas** [comment]
As you mentioned, it was the problem with gzip.
Thanks for reporting.
